CREATE TABLE slideshows
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    image_url  VARCHAR(255),
    caption    TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);